### ISSUE TITLE
Missing index.html

### ISSUE THREAD

**Issue by gpolak** [mitmedialab/Junkyard-Jumbotron#1]
After starting the server (node jjserver.js" I get a 500 error when trying to connect to the server on localhost: 500 Error: ENOENT, No such file or directory '/home/george/git/Junkyard-Jumbotron/public/index.html'

Indeed, the listing of "public" seems to be missing an index page:

george@george-laptop:~/git/Junkyard-Jumbotron$ ls public/
css  favicon.gif  favicon.ico  images  javascript  jumbotrons  markers  robots.txt  samples

Am I missing something?

**Comment by bleppie** [comment]
JJ uses the jade template language, so index.jade in private/views is converted to index.html on the fly.

Try starting node as root, and make sure you aren't running another server, like apache, or make sure change the port in params.js to something other than 80 (8080 for example) and then go to localhost:8080.

**Comment by kkoechley** [comment]
I know this is very old, but I'm having this same error:  500 Error: ENOENT, No such file or directory

I've insured the port isn't the issue - changed port in params.js as well as launching with sudo - all resulting in the same 500 error.  All other node.js apps work.  

Any thoughts?

**Comment by bleppie** [comment]
HI Kevin, I've been off this project for a while, but from what I can
remember, there isn't supposed to be a 'public/index.html'. Requests are
supposed to go to Jade, which uses 'private/views/index.jade'. Make sure
your directory permissions are set correctly so the server has access to
these files.

Best of luck,
Brian

**Comment by workingmatt** [comment]
I found the solution was to use the correct version of nodejs.  I used nvm (apt-get install nvm) to install different versions of node (e.g. nvm install 0.8.25 or nvm install 0.4.12) and switch between them instantly (nvm use 0.4.12). 0.8.x didn't work for me, however 0.4.12 did. That is what got rid of the ENOENT error for me.

I still had a problem getting a picture recognised. I could upload a config photo but it was not recognised.

**Comment by ccardoso** [comment]
I have the server running remember that we need to modified files paramsLocal and params ... but also when i try upload a image i have this error>
ERROR: myJumb controller 0 > Error: Command failed: /bin/sh: 1: gm: not found
Help!!!!!

**Comment by ccardoso** [comment]
sorry I found the problem I no have a graphic magic install... but now I have a new error>
ERROR: myJumb2 controller 0 > Error: Command failed: /bin/sh: 1: python: not found

this is my directory of python > /usr/bin/python2.7

anyone have this problem .... 
Thx
